# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVPParseJson' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVPParseJson

  pod 'PKHUD'
  pod 'Alamofire'

  target 'MVPParseJsonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVPParseJsonUITests' do
    # Pods for testing
  end

end
